version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
#    command: gunicorn webshop.wsgi -b 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
      - db
      - memcached
    environment:
      - "DJANGO_SECRET_KEY=" #  Fill it
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"


      - "BRAINTREE_MERCHANT_ID="  #  Fill it
      - "BRAINTREE_PUBLIC_KEY="  #  Fill it
      - "BRAINTREE_PRIVATE_KEY="  #  Fill it
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  memcached:
    image: "memcached:latest"
    ports:
    - '11211:11211'

volumes:
  postgres_data: